# Generated by Django 5.1.1 on 2024-11-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to="property_images/"),
        ),
    ]
