# Generated by Django 5.1.1 on 2024-11-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_property_property_id_alter_propertyimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="id",
        ),
        migrations.AlterField(
            model_name="property",
            name="property_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
