# Generated by Django 5.1.1 on 2024-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
