# Generated by Django 5.1.1 on 2024-11-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
    ]
